function CSXSWindowType(){}CSXSWindowType._PANEL="Panel";CSXSWindowType._MODELESS="Modeless";CSXSWindowType._MODAL_DIALOG="ModalDialog";EvalScript_ErrMessage="EvalScript error.";function Version(a,b,c,d){this.major=a;this.minor=b;this.micro=c;this.special=d}Version.MAX_NUM=999999999;function VersionBound(a,b){this.version=a;this.inclusive=b}function VersionRange(a,b){this.lowerBound=a;this.upperBound=b}function Runtime(a,b){this.name=a;this.versionRange=b}
function Extension(a,b,c,d,e,f,g,h,k,l,m,n,p,q,r,s){this.id=a;this.name=b;this.mainPath=c;this.basePath=d;this.windowType=e;this.width=f;this.height=g;this.minWidth=h;this.minHeight=k;this.maxWidth=l;this.maxHeight=m;this.defaultExtensionDataXml=n;this.specialExtensionDataXml=p;this.requiredRuntimeList=q;this.isAutoVisible=r;this.isPluginExtension=s}function CSEvent(a,b,c,d){this.type=a;this.scope=b;this.appId=c;this.extensionId=d}CSEvent.prototype.data="";function SystemPath(){}
SystemPath.USER_DATA="userData";SystemPath.COMMON_FILES="commonFiles";SystemPath.MY_DOCUMENTS="myDocuments";SystemPath.APPLICATION="application";SystemPath.EXTENSION="extension";SystemPath.HOST_APPLICATION="hostApplication";function ColorType(){}ColorType.RGB="rgb";ColorType.GRADIENT="gradient";ColorType.NONE="none";function RGBColor(a,b,c,d){this.red=a;this.green=b;this.blue=c;this.alpha=d}function Direction(a,b){this.x=a;this.y=b}function GradientStop(a,b){this.offset=a;this.rgbColor=b}
function GradientColor(a,b,c,d){this.type=a;this.direction=b;this.numStops=c;this.arrGradientStop=d}function UIColor(a,b,c){this.type=a;this.antialiasLevel=b;this.color=c}function AppSkinInfo(a,b,c,d,e,f,g){this.baseFontFamily=a;this.baseFontSize=b;this.appBarBackgroundColor=c;this.panelBackgroundColor=d;this.appBarBackgroundColorSRGB=e;this.panelBackgroundColorSRGB=f;this.systemHighlightColor=g}
function HostEnvironment(a,b,c,d,e,f,g){this.appName=a;this.appVersion=b;this.appLocale=c;this.appUILocale=d;this.appId=e;this.isAppOnline=f;this.appSkinInfo=g}function HostCapabilities(a,b,c,d,e){this.EXTENDED_PANEL_MENU=a;this.EXTENDED_PANEL_ICONS=b;this.DELEGATE_APE_ENGINE=c;this.SUPPORT_HTML_EXTENSIONS=d;this.DISABLE_FLASH_EXTENSIONS=e}function ApiVersion(a,b,c){this.major=a;this.minor=b;this.micro=c}function MenuItemStatus(a,b,c){this.menuItemLabel=a;this.enabled=b;this.checked=c}
function ContextMenuItemStatus(a,b,c){this.menuItemID=a;this.enabled=b;this.checked=c}function CSInterface(){}CSInterface.THEME_COLOR_CHANGED_EVENT="com.adobe.csxs.events.ThemeColorChanged";CSInterface.prototype.hostEnvironment=JSON.parse(window.__adobe_cep__.getHostEnvironment());CSInterface.prototype.getHostEnvironment=function(){return this.hostEnvironment=JSON.parse(window.__adobe_cep__.getHostEnvironment())};CSInterface.prototype.closeExtension=function(){window.__adobe_cep__.closeExtension()};
CSInterface.prototype.getSystemPath=function(a){a=decodeURI(window.__adobe_cep__.getSystemPath(a));var b=this.getOSInformation();0<=b.indexOf("Windows")?a=a.replace("file:///",""):0<=b.indexOf("Mac")&&(a=a.replace("file://",""));return a};CSInterface.prototype.evalScript=function(a,b){if(null==b||void 0==b)b=function(a){};window.__adobe_cep__.evalScript(a,b)};CSInterface.prototype.getApplicationID=function(){return this.hostEnvironment.appId};CSInterface.prototype.getHostCapabilities=function(){return JSON.parse(window.__adobe_cep__.getHostCapabilities())};
CSInterface.prototype.dispatchEvent=function(a){"object"==typeof a.data&&(a.data=JSON.stringify(a.data));window.__adobe_cep__.dispatchEvent(a)};CSInterface.prototype.addEventListener=function(a,b,c){window.__adobe_cep__.addEventListener(a,b,c)};CSInterface.prototype.removeEventListener=function(a,b,c){window.__adobe_cep__.removeEventListener(a,b,c)};CSInterface.prototype.requestOpenExtension=function(a,b){window.__adobe_cep__.requestOpenExtension(a,b)};
CSInterface.prototype.getExtensions=function(a){a=JSON.stringify(a);a=window.__adobe_cep__.getExtensions(a);return JSON.parse(a)};CSInterface.prototype.getNetworkPreferences=function(){var a=window.__adobe_cep__.getNetworkPreferences();return JSON.parse(a)};
CSInterface.prototype.initResourceBundle=function(){for(var a=JSON.parse(window.__adobe_cep__.initResourceBundle()),b=document.querySelectorAll("[data-locale]"),c=0;c<b.length;c++){var d=b[c],e=d.getAttribute("data-locale");if(e)for(var f in a)if(0==f.indexOf(e)){var g=a[f];if(f.length==e.length)d.innerHTML=g;else if("."==f.charAt(e.length)){var h=f.substring(e.length+1);d[h]=g}}}return a};CSInterface.prototype.dumpInstallationInfo=function(){return window.__adobe_cep__.dumpInstallationInfo()};
CSInterface.prototype.getOSInformation=function(){var a=navigator.userAgent;if("Win32"==navigator.platform||"Windows"==navigator.platform){var b="Windows",c="";-1<a.indexOf("Windows")&&(-1<a.indexOf("Windows NT 5.0")?b="Windows 2000 ":-1<a.indexOf("Windows NT 5.1")?b="Windows XP ":-1<a.indexOf("Windows NT 5.2")?b="Windows Server 2003 ":-1<a.indexOf("Windows NT 6.0")?b="Windows Vista ":-1<a.indexOf("Windows NT 6.1")?b="Windows 7 ":-1<a.indexOf("Windows NT 6.2")&&(b="Windows 8 "),c=-1<a.indexOf("WOW64")?
"64-bit":"32-bit");return b+c}return"MacIntel"==navigator.platform||"Macintosh"==navigator.platform?(c="Mac OS X",b=new String,b=a,-1<b.indexOf("Mac OS X")&&(a=b.indexOf(")")-b.indexOf("Mac OS X"),c=b.substr(b.indexOf("Mac OS X"),a).replace("_","."),c=c.replace("_",".")),c):"Unknown Operation System"};CSInterface.prototype.openURLInDefaultBrowser=function(a){return cep.util.openURLInDefaultBrowser(a)};CSInterface.prototype.getExtensionID=function(){return window.__adobe_cep__.getExtensionId()};
CSInterface.prototype.getScaleFactor=function(){return window.__adobe_cep__.getScaleFactor()};CSInterface.prototype.setScaleFactorChangedHandler=function(a){window.__adobe_cep__.setScaleFactorChangedHandler(a)};CSInterface.prototype.getCurrentApiVersion=function(){return JSON.parse(window.__adobe_cep__.getCurrentApiVersion())};CSInterface.prototype.setPanelFlyoutMenu=function(a){"string"==typeof a&&window.__adobe_cep__.invokeSync("setPanelFlyoutMenu",a)};
CSInterface.prototype.updatePanelMenuItem=function(a,b,c){var d=!1;this.getHostCapabilities().EXTENDED_PANEL_MENU&&(a=new MenuItemStatus(a,b,c),d=window.__adobe_cep__.invokeSync("updatePanelMenuItem",JSON.stringify(a)));return d};CSInterface.prototype.setContextMenu=function(a,b){"string"==typeof a&&window.__adobe_cep__.invokeAsync("setContextMenu",a,b)};
CSInterface.prototype.updateContextMenuItem=function(a,b,c){a=new ContextMenuItemStatus(a,b,c);ret=window.__adobe_cep__.invokeSync("updateContextMenuItem",JSON.stringify(a))};
